export const API_HOME = 'https://covid19.th-stat.com/th/api'
export const API_TODAY = 'https://covid19.th-stat.com/api/open/today'
export const API_TIMELINE = 'https://covid19.th-stat.com/api/open/timeline'
export const API_CASES = 'https://covid19.th-stat.com/api/open/cases'
export const API_CASES_SUMMARY = 'https://covid19.th-stat.com/api/open/cases/sum'
export const API_AREA = 'https://covid19.th-stat.com/api/open/area'
export const GITHUB_URL = 'https://github.com/phumoonlight/covid-tracker-th'
